import * as https from 'https';
import * as path from 'path';
import * as fs from 'fs';
import * as winston from 'winston';
import { createLogger } from './logger';

/**
 * AI Agent Service for generating feature files using Claude or OpenAI
 * Supports both Claude (Anthropic) and OpenAI APIs
 */

interface AIConfig {
  provider: 'claude' | 'openai';
  apiKey: string;
  model: string;
  baseUrl?: string;
}

/**
 * Get AI configuration from environment variables or config file
 */
function getAIConfig(): AIConfig | null {
  // Try environment variables first
  const provider = process.env.AI_PROVIDER as 'claude' | 'openai';
  const apiKey = process.env.AI_API_KEY;

  if (!provider || !apiKey) {
    console.warn('⚠️  AI_PROVIDER and AI_API_KEY environment variables not set');
    console.warn('   Please set these to enable automatic feature file generation:');
    console.warn('   - AI_PROVIDER: "claude" or "openai"');
    console.warn('   - AI_API_KEY: Your API key');
    return null;
  }

  return {
    provider,
    apiKey,
    model: provider === 'claude' 
      ? process.env.AI_MODEL || 'claude-3-sonnet-20240229'
      : process.env.AI_MODEL || 'gpt-4-turbo-preview'
  };
}

/**
 * Call Claude API to generate feature file
 */
async function callClaudeAPI(prompt: string, config: AIConfig): Promise<string> {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify({
      model: config.model,
      max_tokens: 4096,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    });

    const options = {
      hostname: 'api.anthropic.com',
      path: '/v1/messages',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
        'x-api-key': config.apiKey,
        'anthropic-version': '2023-06-01'
      }
    };

    const req = https.request(options, (res) => {
      let responseData = '';

      res.on('data', chunk => {
        responseData += chunk;
      });

      res.on('end', () => {
        try {
          if (res.statusCode === 200) {
            const response = JSON.parse(responseData);
            const content = response.content?.[0]?.text || '';
            console.log('✅ Feature file generated by Claude');
            resolve(content);
          } else {
            const errorMsg = JSON.parse(responseData).error?.message || 'Unknown error';
            reject(new Error(`Claude API error: ${res.statusCode} - ${errorMsg}`));
          }
        } catch (e) {
          reject(new Error(`Failed to parse Claude response: ${e}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/**
 * Call OpenAI API to generate feature file
 */
async function callOpenAIAPI(prompt: string, config: AIConfig): Promise<string> {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify({
      model: config.model,
      messages: [
        {
          role: 'system',
          content: 'You are a QA automation expert specializing in generating Gherkin feature files for Behavioral Driven Development. Generate comprehensive, production-ready feature files with proper syntax, meaningful scenarios, and detailed step definitions.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 4096
    });

    const options = {
      hostname: 'api.openai.com',
      path: '/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
        'Authorization': `Bearer ${config.apiKey}`
      }
    };

    const req = https.request(options, (res) => {
      let responseData = '';

      res.on('data', chunk => {
        responseData += chunk;
      });

      res.on('end', () => {
        try {
          if (res.statusCode === 200) {
            const response = JSON.parse(responseData);
            const content = response.choices?.[0]?.message?.content || '';
            console.log('✅ Feature file generated by OpenAI');
            resolve(content);
          } else {
            const errorMsg = JSON.parse(responseData).error?.message || 'Unknown error';
            reject(new Error(`OpenAI API error: ${res.statusCode} - ${errorMsg}`));
          }
        } catch (e) {
          reject(new Error(`Failed to parse OpenAI response: ${e}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/**
 * Generate feature file using AI agent
 */
export async function generateFeatureFileWithAI(agentPrompt: string): Promise<string | null> {
  const logger = createLogger('ai-agent-service');
  const config = getAIConfig();

  if (!config) {
    console.log('\n⏭️  Skipping automatic feature file generation');
    console.log('   To enable: Set AI_PROVIDER and AI_API_KEY environment variables');
    logger.warn('⏭️  Skipping automatic feature file generation - AI_PROVIDER or AI_API_KEY not set');
    return null;
  }

  try {
    console.log('\n🤖 Contacting Jira Test Automation Agent...');
    console.log(`   Provider: ${config.provider}`);
    console.log(`   Model: ${config.model}`);
    logger.info(`🤖 Contacting Jira Test Automation Agent...`);
    logger.info(`   Provider: ${config.provider}`);
    logger.info(`   Model: ${config.model}`);

    let featureContent: string;

    if (config.provider === 'claude') {
      featureContent = await callClaudeAPI(agentPrompt, config);
    } else if (config.provider === 'openai') {
      featureContent = await callOpenAIAPI(agentPrompt, config);
    } else {
      throw new Error(`Unknown AI provider: ${config.provider}`);
    }

    return featureContent;
  } catch (error) {
    console.error('❌ AI Generation Error:', error instanceof Error ? error.message : error);
    console.log('   Continuing without automatic feature file generation...');
    logger.error(`❌ AI Generation Error: ${error instanceof Error ? error.message : error}`);
    logger.info('Continuing without automatic feature file generation...');
    return null;
  }
}

/**
 * Extract feature file content from AI response
 * Removes markdown code blocks if present
 */
export function extractFeatureContent(aiResponse: string): string {
  // Remove markdown code blocks if present
  let content = aiResponse.trim();

  // Remove ```gherkin or ``` at start
  content = content.replace(/^```(?:gherkin)?\n?/, '');

  // Remove ``` at end
  content = content.replace(/\n?```$/, '');

  return content.trim();
}

/**
 * Save generated feature file to disk
 */
export function saveGeneratedFeatureFile(
  content: string,
  storyId: string,
  outputDir: string = '../specs'
): string {
  const logger = createLogger('ai-agent-service');
  
  try {
    // Ensure output directory exists
    const fullOutputDir = path.join(__dirname, outputDir);
    if (!fs.existsSync(fullOutputDir)) {
      fs.mkdirSync(fullOutputDir, { recursive: true });
    }

    // Generate filename
    const filename = `${storyId.toLowerCase().replace(/\s+/g, '-')}.feature`;
    const filepath = path.join(fullOutputDir, filename);

    // Save the file
    fs.writeFileSync(filepath, content, 'utf-8');

    console.log(`✅ Feature file saved successfully:`);
    console.log(`   ${filepath}`);
    console.log(`   Use: npm test`);
    logger.info(`✅ Feature file saved successfully: ${filepath}`);

    return filepath;
  } catch (error) {
    console.error(`❌ Error saving feature file: ${error}`);
    logger.error(`❌ Error saving feature file: ${error}`);
    throw error;
  }
}

export default {
  generateFeatureFileWithAI,
  extractFeatureContent,
  saveGeneratedFeatureFile,
  getAIConfig
};
